spring.application.name=spring-mvc

spring.datasource.url=jdbc:postgresql://localhost:5432/lesson_spring_basic
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA（エンティティやスキーマの扱い設定）
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true